import type { Metadata } from "next";
import { Noto_Serif, Lobster } from "next/font/google";
import "./globals.css";
import classNames from "classnames";
import NavBar from "@/components/NavBar";

const noto = Noto_Serif({ subsets: ["latin"], variable: "--font-noto" });
const lob = Lobster({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lob",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(noto.className, lob.variable)}>
        <header>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
